### ISSUE TITLE
Implement "is-oracle-tx" support in Cosmos SDK v0.45.11

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/cosmos-sdk#1]
**Problem definition**
We need to implement the "is-oracle-tx" logic in Cosmos SDK v0.45.11 if we want to upgrade without breaking the Oracle modules enforced priority, which would lead to validators getting slashed & jailed for missing votes.

**Acceptance criteria**
Support "is-oracle-tx"  priority logic in Cosmos-SDK

**Additional context**
- [x] Implement "oracle mempool priority" logic based on release/0.45.x branch
- [x] Integrate cosmos SDK with github.com/classic-terra/tendermint v0.34.24-terra.0

**Comment by inon-man** [comment]
[Tendermint ](https://github.com/classic-terra/tendermint/releases/tag/v0.34.24-terra.0) is working for v1.0.4 (current mainnet)

**Comment by inon-man** [comment]
I merged cosmos-sdk v0.44.8 into classic-terra/cosmos-sdk/dev/v0.44.x and it is also working

**Comment by ZaradarBH** [comment]
https://github.com/cosmos/gaia/blob/main/docs/migration/cosmoshub-4-v7-Theta-upgrade.md

**Comment by ZaradarBH** [comment]
I implemented a branch with the oracle mempool priority logic YunSuk wrote back in December 2021. You can find the PR here @ https://github.com/classic-terra/cosmos-sdk/pull/5
